#!/bin/bash

export LANG=C
TOPIC=$2
CORP=$3

# $1 -> tr0.seed.doc: acquisition
# concordance.tr0.seed.doc: tr0.seed.doc      1 acquisit
N=`find $1 -type f | wc -l`

MODE=$MODE find $1 -type f -exec "./dosteminline" {} \; | sort -k3 > $TOPIC/concordance.$1

#tfdf.tr0.seed.doc.sort: acquisit 146 1003 tr0.seed.doc 1
cat -n $CORP.df | join -13 -23 - $TOPIC/concordance.$1 | sort -k4,4 -k2,2n > $TOPIC/tfdf.$1.sort

N=`cat N`
echo N $N

#svm.tr0.seed.doc.fil: tr0.seed.doc 146:1.00000000
./dotfidfinline $N < $TOPIC/tfdf.$1.sort > $TOPIC/svm.$1.fil
# python2 doc2vec.py "$TOPIC"/svm.$1.fil "$CORP".english_analyzer.300.bin "$CORP".dict x
python2 doc2vec.py $TOPIC/tfdf.$1.sort "$CORP".english_analyzer.300.bin x
mv x "$TOPIC"/svm.$1.fil
